### PR TITLE
Add support -privileged when create swarm service.

### PR DESCRIPTION
**Pull request by sy1124kim**
When create tizen container, we need privileged=true.
But swarm and swarmkit does not support this.

1. Add privileged field in ContainerSpec.
2. Pass privileged to HostConfig when create container.
3. Add container options in docker-engine, docker-client.

Signed-off-by: sy1124.kim <sy1124.kim@samsung.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Namsulee** [comment]
How to apply the option of privileged?
docker service create --privileged 10.113.62.204:443/headless:v0.1 ?
or docker service create --privileged=true 10.113.62.204:443/headless:v0.1 ? 
or both are correct? Also, add up in comment regarding **.proto** what it is and how to make it. It will helpful to understand how to apply the option into docker.

**Comment by sy1124kim** [comment]
" --privileged=false: Give extended privileges to this container "
ex) docker service create --privileged 10.113.62.204:443/headless:v0.1 
ex) docker service create --privileged=false  10.113.62.204:443/headless:v0.1

<<proto buf>>
Protocol buffers are a language-neutral, platform-neutral extensible mechanism for serializing structured data. (developer site : https://developers.google.com/protocol-buffers/)

**Comment by jiehwan** [comment]
in my understanding, swarmkit relative files(/api/specs.pb.go, proto.go) are extracted after building swarkit independently. 
so please add belows.
1. update to the dockzen/swarmkit github source and make comment in README.md
2. add commit comments regarding the swarmkit generations.
if someone need to change relative to swamkit, this comment documentation will be very helpful.

**Comment by sy1124kim** [comment]
Update source code and README.md. (https://github.com/dockzen/swarmkit)

**Pull request merged**
